### PR TITLE
update install instructions + slides

### PR DESCRIPTION
**Pull request by haesleinhuepf**
here come small updates regarding installation instructions (thanks for figuring that out @zoccoler !) and slides as discussed with @jni

### CODE REVIEW

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

Once #11 is merged, could you refer or also mention the installation using the `.yml` file for this course?
It contains devbio-napari 😃

**Comment by zoccoler** [comment]
You may also consider using the [new logo](https://github.com/LIBREhub/napari-LatAm-workshop-2023/blob/main/docs/LatAmBio_Logo.png) for this course in the slides 😉

**Comment by jni** [comment]
Yes ideally we only have One True Environment for the whole workshop?

**Comment by haesleinhuepf** [comment]
> One True Environment 

Which? Can you provide a link?

Thanks!

**Comment by jni** [comment]
On phone but it was added in #11. It's at the root of the repo.

**Comment by zoccoler** [comment]
Thanks @haesleinhuepf !
Is it ready to merger ?

**Comment by haesleinhuepf** [comment]
Hi @zoccoler ,

I'm done with the changes we discussed. Would you  mind having another look and ideally merge?

* Removed devbio-napari installation instructions
* Added APOC demo
* Remove duplicated napari-assistant/export-notebook exercise documents
* Updated TOC
* Added link to PPTX slides on f1000

Thanks! I'm looking forward to the course!

Best,
Robert

**Pull request merged**
